- name: Check whether desired organizationalUnit LDAP entry exists
  command: ldapsearch -x -b ou={{ou_name}},{{base_dn}} -s base
  ignore_errors: true
  register: ldapsearch_orgunit
  tags:
    - ldap

- name: Add organizationalUnit LDAP entry (1/2)
  template: src=ou.ldif.j2 dest=/tmp/ou.ldif owner=root group=root mode=0644
  when: ldapsearch_orgunit | failed
  tags:
    - ldap

- name: Add organizationalUnit LDAP entry (2/2)
  command: ldapadd -D cn=admin,{{base_dn}} -w {{ domain_ldap_admin_pass }} -f /tmp/ou.ldif
  when: ldapsearch_orgunit | failed
  tags:
    - ldap

- name: Remove LDIF temporary file for organizationalUnit entry
  file: path=/tmp/ou.ldif state=absent
  tags:
    - ldap
